const fs = require('fs');
const packageJson = require('../package.json');

const content = `// Auto-generated by build script
export const VERSION = '${packageJson.version}';
`;

fs.writeFileSync('./src/version.ts', content);
console.log(`Version file created with version ${packageJson.version}`);